# ============================================================
#   data.py — Saara data yahan hai (owner info + Q&A)
#   Sirf yeh file edit karo naye sawal/jawab ke liye!
# ============================================================

OWNER_INFO = {
    "name":      "Muhammad Naeem",
    "profession": "Sales Man",
    "contact":   "03284111800",
    "location":  "Mailsi, Pakistan",
    "whatsapp":  "03284111800",
}

QA_DATA = [
    # ── OWNER / CHATBOT INFO ─────────────────────────────────────
    (["owner name","aapka maalik","kiska chatbot","kis ka chatbot","who made","tumhara maalik"],
     f"Yeh chatbot {OWNER_INFO['name']} ka hai. Woh Mailsi ke ek mashhoor Sales Man hain."),
    (["contact","number","phone","call","whatsapp","rabta","mobile"],
     f"{OWNER_INFO['name']} se rabta karne ke liye call ya WhatsApp karein: {OWNER_INFO['contact']}"),
    (["location","address","kahan","mailsi","where","jagah","city","shehar"],
     f"{OWNER_INFO['name']} Mailsi, Pakistan mein hain. Mailsi Vehari district ka ek mashoor shehar hai."),
    (["profession","kaam","job","occupation","salesman","sale man","kya karte","pehsha"],
     f"{OWNER_INFO['name']} ek Sales Man hain. Woh products bechne aur customers se milne ka kaam karte hain."),
    (["who are you","aap kaun","chatbot kaun","tum kaun","main kaun","bot kaun"],
     f"Main {OWNER_INFO['name']} ka Sales Chatbot hun! Sales, marketing aur karobar ke barey mein poochhein."),
    (["aapka naam","your name","chatbot naam","bot naam","name"],
     f"Mera naam 'Sales Bot' hai aur mera maalik {OWNER_INFO['name']} hai — Mailsi ke mashhoor Sales Man!"),

    # ── SALES BASICS ─────────────────────────────────────────────
    (["salesman kya","sales man kya hota","salesman matlab","sales job"],
     "Sales Man woh hota hai jo customers ko products ya services bechta hai. Yeh ek art hai jisme communication aur persuasion zaroori hai."),
    (["sales kaise karein","selling tips","product kaise bechain","sale karna"],
     "Achi sale ke liye: customer ki zaroorat samjho, product ke fayde batao, price sahi rakho, trust banao aur follow-up karo. Smile hamesha rakho!"),
    (["good salesman","acha salesman kaise bane","sales skills"],
     "Acha Sales Man banne ke liye: sunne ki aadat banao, customer se dosti karo, product ka ilm rakho, reject hone se mat daro aur hamesha positive raho."),
    (["sales target","target kaise poora karein","monthly target"],
     "Target poora karne ke liye: daily plan banao, leads track karo, purane customers se follow-up karo aur naye customers dhoondho. Consistency key hai."),
    (["cold calling","phone par sale","call karna customers ko"],
     "Cold calling mein: pehle introduce karo, customer ki zaroorat pooch, product ka faida batao aur meeting ki request karo. Rejection normal hai — carry on!"),
    (["door to door","ghar ghar jana","field sales","direct sales"],
     "Door-to-door sales mein: smart kapde pehno, smile rakho, jaldi point pe aao, faida batao aur objection handle karo. Mulaqat mein confidence zaroori hai."),
    (["rejection","na suno","customer na kare","sales reject"],
     "Rejection sales ka hissa hai. Har 'na' aapko ek 'haan' ke qareeb karta hai. Seekho, improve karo aur agli call pe jao. Never give up!"),
    (["customer service","grahak sewa","customer care","after sales"],
     "Customer service sales se zyada zaroori hai. Khush customer dobara aata hai aur doosron ko bhi bhejta hai. Har complaint ko opportunity samjho."),
    (["product knowledge","maal ka ilm","apna product jaano"],
     "Apne product ka poora ilm rakho: features, price, competitors se farq aur customer ke liye fayde. Ilm se confidence aata hai aur sale hoti hai."),
    (["negotiation","mol tol","price negotiate","qeemat tay karna"],
     "Negotiation mein: pehle apni minimum price tay karo, customer ki limit samjho, value dikhao aur win-win deal banao. Zyada mat jhuko pehle hi."),
    (["closing deal","deal close karna","sale pakki karna"],
     "Deal close karne ke liye: customer ke signals dekho, urgency create karo ('limited stock'), benefit summarize karo aur directly pooch 'kab lena chahein ge?'"),
    (["follow up","customer ko follow karna","dobara call"],
     "Follow-up sales ki jaan hai! Pehli meeting ke 24 ghante mein message karo. Weekly touch point rakho jab tak deal na ho jaye."),
    (["commission","sales commission","kitni kamaai","income salesman"],
     "Sales Man ki income = basic salary + commission. Commission usually 5-15% hoti hai. Zyada sale = zyada commission. Top salesmen bahut kama sakte hain."),
    (["sales territory","area","apna area","field"],
     "Apna territory systematically cover karo. Map banao, routes plan karo aur ek area mein sab customers visit karo. Time aur petrol bachega."),
    (["daily routine","roz ka kaam","sales schedule","planning"],
     "Sales Man ki routine: subah planning, customer calls/visits, lunch break, afternoon visits, evening reporting, raat mein next day ki planning."),
    (["sales report","report banana","daily report","manager ko report"],
     "Roz ki report mein: kitne customers mile, kitni sale hui, koi pending deals, aur challenges kya the. Honest reporting se manager ka trust banta hai."),
    (["sales team","team mein kaam","team leader"],
     "Team mein kaam karne ke liye: apne saathi ki madad karo, experience share karo, positive rahio aur competition ko healthy rakho. Team ki jeet sab ki jeet hai."),
    (["b2b sales","business to business","company ko bechna"],
     "B2B sales mein: decision maker tak pahuncho, ROI dikhao, proper presentation do aur follow-up professional rakho. B2B deals badi hoti hain par waqt lagta hai."),
    (["b2c sales","consumer sales","grahak ko bechna","retail"],
     "B2C mein seedha customer se baat hoti hai. Emotional appeal zyada kaam karta hai. Quick decisions hote hain. Price aur convenience important hai."),
    (["online sales","digital sales","social media sales","ecommerce"],
     "Online sales ke liye: Facebook/Instagram shop, OLX listings, WhatsApp business use karo. Photos achi rakho, prices clear likho aur fast reply karo."),
    (["whatsapp business","whatsapp se sale","whatsapp marketing"],
     "WhatsApp Business se sale: catalog banao, broadcast lists use karo, quick replies set karo aur status mein products dikhao. Free aur effective tool hai."),
    (["facebook marketing","facebook ads","fb se sale"],
     "Facebook par: business page banao, achi photos dalo, customer reviews share karo. Paid ads se zyada reach milti hai. Budget kam bhi kaam karta hai."),
    (["customer trust","trust banana","bharosa","loyalty"],
     "Trust banane ke liye: hamesha sach bolo, promise poori karo, waqt par deliver karo aur problems jaldi solve karo. Trust ek baar bana liya toh customer hamesha aata hai."),
    (["complaint handling","shikayat","customer naraaz","upset customer"],
     "Naraaz customer handle karne ke liye: seedha suno, maafi mango, solution do aur follow-up karo. Acha solution ek loyal customer bana deta hai."),
    (["upselling","cross selling","zyada sale karna","add on"],
     "Upselling mein: jo customer kharid raha hai usse behtareen version dikhao. Cross-sell mein related product suggest karo. 'Iske saath yeh bhi acha hai' kaho."),
    (["referral","hawala","dost ko lana","word of mouth"],
     "Referral sabse sasti marketing hai! Khush customers se kaho: 'Agar koi dost chahiye toh mera number do.' Incentive bhi de sakte ho."),
    (["sales pitch","apni baat karna","presentation","pitching"],
     "Achi pitch mein: pehle problem batao, phir apna solution, phir faida, phir proof (customers) aur aakhir mein call to action. Practice karo!"),
    (["objection handling","aitiraaz","customer ka jawab","why so expensive"],
     "Objection handle karne ke liye: pehle suno, samjho, phir jawab do. 'Mehnga hai' pe kaho: 'Value dekho price nahi — yeh aapke X masla hal karega.'"),

    # ── SALES PRODUCTS & INDUSTRIES ─────────────────────────────
    (["fmcg sales","grocery","daily items","rozana ki cheezein"],
     "FMCG sales mein rozana istemal ki cheezein shamil hain. Quick turnover hota hai. Distribution aur availability key hai. Mailsi jaise shehron mein achi demand hai."),
    (["medicine sales","pharma","dawai bechna","medical rep"],
     "Pharma sales mein doctors aur pharmacists ko dawaiyan recommend karni hoti hain. Product knowledge aur professional image zaroori hai. Acha commission milta hai."),
    (["real estate sales","zameen bechna","property sales","plot bechna"],
     "Property sales mein: zameen ki documentation samjho, area ka knowledge rakho, buyer aur seller dono ka faida socho aur commission 1-2% milta hai."),
    (["car sales","gaadi bechna","vehicle sales","auto sales"],
     "Car sales mein: test drive offer karo, financing options batao, comparison karo aur emotional appeal use karo. Showroom presentation important hai."),
    (["insurance sales","beema bechna","insurance agent"],
     "Insurance sales mushkil hai par rewarding hai. Benefits clearly samjhao, fear nahi value dikhao aur long-term relationship banao. Recurring income milti hai."),
    (["electronics sales","electronic bechna","mobile tv"],
     "Electronics sales mein: specifications simple language mein batao, demo do, warranty explain karo aur after-sales support ka bharosa do."),
    (["agriculture products","kheti ka samaan","seeds fertilizer","seeds bechna"],
     "Agriculture products bechne ke liye Mailsi perfect jagah hai! Kisaanon ke problems samjho, product ka faida crop yield se jodo aur trust banao."),
    (["textile sales","kapra bechna","cloth sales"],
     "Textile sales mein: fabric quality dikhao, latest designs rakho, bulk orders pe discount do aur seasonal trends follow karo. Mailsi area mein textile demand hai."),
    (["food products","khaane ka samaan","food sales"],
     "Food products bechne mein: freshness aur quality par focus karo, hygiene maintain karo aur bulk/wholesale rates retailers ko do. Repeat orders aate hain."),
    (["solar products","solar sales","solar panels bechna"],
     "Solar products ki demand barh rahi hai. Load shedding ki wajah se har ghar solar chahta hai. ROI calculator dikhao — investment 2-3 saal mein wapas aata hai."),

    # ── MARKETING ────────────────────────────────────────────────
    (["marketing kya hai","marketing matlab","marketing aur sales farq"],
     "Marketing customers tak paigham pohanchana hai, Sales unhe khareedne par raazi karna hai. Marketing leads banati hai, Sales unhe close karti hai."),
    (["brand awareness","apna brand banana","logo","branding"],
     "Brand banane ke liye: ek unique naam/logo rakho, consistent color aur tone use karo aur hamesha quality deliver karo. Trust se brand banta hai."),
    (["flyer","pamphlet","poster marketing","printout marketing"],
     "Flyer marketing mein: bold headline, clear offer, contact number aur CTA (call to action) zaroori hai. Mailsi mein local markets mein distribute karo."),
    (["sms marketing","text message marketing","bulk sms"],
     "Bulk SMS marketing: cheap aur effective hai. Short message, clear offer aur number daalo. Pakistan mein 90%+ log SMS padhte hain. Telcos se service lein."),
    (["exhibition","mela","trade show","stall"],
     "Trade shows mein: colorful stall banao, free samples do, business cards rakho aur leads collect karo. Mailsi ke local mele aur shows great opportunities hain."),
    (["discount","offer","sale offer","promotion"],
     "Discount strategy: limited time offer urgency create karta hai. '20% off sirf aaj' zyada asar karta hai. Margin ka khayal rakho — zyada discount ghata bhi deta hai."),
    (["seasonal sales","eid sale","tyoharon mein sale"],
     "Eid, Ramzan, winter/summer season mein sales peak hoti hain. Pehle se stock tayaar rakho, special offers banao aur marketing mein tezi lao."),
    (["pricing strategy","qeemat kaise tay karein","price setting"],
     "Qeemat tay karte waqt: cost + margin calculate karo, competitors check karo aur customer ki willingness to pay samjho. Na zyada na kam — balanced price rakho."),

    # ── MAILSI INFO ──────────────────────────────────────────────
    (["mailsi kahan","mailsi city","mailsi location","mailsi shehar"],
     "Mailsi Vehari District, Punjab Pakistan mein hai. Yeh ek agricultural aur tijaarati shehar hai. Cotton aur wheat ki wajah se mashoor hai."),
    (["mailsi market","mailsi bazaar","mailsi business"],
     "Mailsi mein grain market, cloth market aur general bazaar hain. Agriculture products ki achi demand hai. Local karobar bahut active hai."),
    (["mailsi agriculture","mailsi kheti","mailsi crops"],
     "Mailsi mein cotton, wheat, sugarcane aur sunflower ki kheti hoti hai. Fertile zameen aur canal system ki wajah se achi paidawar hoti hai."),
    (["mailsi population","mailsi aabadi"],
     "Mailsi ki aabadi takriban 2-3 lakh hai. Yeh Vehari district ka ek important shehar hai. Agricultural community dominant hai."),
    (["mailsi transport","mailsi safar","mailsi se kahan"],
     "Mailsi se Vehari, Multan aur Bahawalpur asaani se jaaya ja sakta hai. Roads aur local transport available hai."),
    (["mailsi hospital","sehat mailsi","hospital mailsi"],
     "Mailsi mein DHQ Hospital aur kuch private clinics hain. Badi beemari ke liye Vehari ya Multan jaana padta hai."),
    (["mailsi school","education mailsi","mailsi college"],
     "Mailsi mein government schools, colleges aur kuch private institutes hain. Education ka standard dheere dheere behtar ho raha hai."),
    (["mailsi weather","mailsi mosam","mailsi garmi"],
     "Mailsi mein Punjab jaisi garmi hoti hai. Garmiyan bohat shadeed hoti hain. Sardiyan moderate hoti hain. Farmers mosam ke mutabiq kheti karte hain."),
    (["vehari","vehari district","vehari info"],
     "Vehari District mein Mailsi, Vehari city aur Burewala shamil hain. Yeh poora area agricultural hai aur cotton belt ka hissa hai."),

    # ── BUSINESS & ENTREPRENEURSHIP ──────────────────────────────
    (["apna karobar","business shuru karna","khud ka kaam","startup"],
     "Apna karobar shuroo karne ke liye: idea socho, market check karo, chhota shuroo karo, capital ka intizaam karo aur risk le. Sales experience karobar mein bahut kaam aati hai."),
    (["business plan","karobar ka plan","business idea"],
     "Business plan mein: product/service kya hai, target customer kaun hai, competition kaun hai, pricing kya hogi aur marketing kaise hogi — yeh sab shamil karo."),
    (["investment","sarmaya lagana","paisay invest karna"],
     "Investment se pehle: risk samjho, market study karo aur chhote se shuroo karo. Sales experience wala banda business mein zyada successful hota hai."),
    (["profit loss","munafa ghata","break even"],
     "Munafa = Revenue - Cost. Break-even woh point hai jahan loss zero ho. Jab tak break-even nahi aata tab tak business mein investment control mein rakho."),
    (["business loan","karobar ke liye loan","bank loan business"],
     "Karobar ke liye: Bank of Punjab, SMEDA, Kamyab Jawan Program se loan mil sakta hai. Business plan aur collateral zaroori hota hai."),
    (["distribution","maal pahunchana","supply chain","distributor"],
     "Distributor woh hota hai jo company se maal le kar retailers tak pahunchata hai. Sales Man ka career distributor banne mein badal sakta hai — bahut munafa hai."),
    (["wholesale","thokhay mein","wholesale market","bulk buying"],
     "Wholesale mein zyada maal ek saath liya/becha jaata hai. Per unit cost kam hoti hai. Mailsi mein grain aur cotton ki wholesale kaafi hoti hai."),
    (["retail","dukaan","retail shop","shopkeeper"],
     "Retail mein directly consumer ko becha jaata hai. Dukaan par achi display, customer service aur credit policy important factors hain."),
    (["franchise","franchise business","chain business"],
     "Franchise mein kisi mashoor brand ka license le kar apna outlet kholte hain. Risk kam hota hai kyunki brand already mashoor hai. Investment zyada lag sakti hai."),
    (["mlm","network marketing","direct marketing","pyramid"],
     "Network marketing mein product ke saath network build karna hota hai. Careful rahein — legitimate MLM aur fraud mein farq karna zaroori hai. Research zaroor karein."),

    # ── COMMUNICATION SKILLS ─────────────────────────────────────
    (["communication skills","baat karna","communication","bolna"],
     "Communication skills ke liye: clearly bolna, sunnna seekho, body language theek rakho, eye contact banao aur simple language use karo. Practice makes perfect."),
    (["confidence","khud aitmadi","self confidence","darna nahi"],
     "Confidence ke liye: apna product jaano, practice karo, rejection se darna nahi, daily affirmations karo aur har choti jeet celebrate karo."),
    (["public speaking","logo ke saamne bolna","presentation skills"],
     "Public speaking mein: practice karo, slow bolna, audience ko dekho, pauses use karo aur stories sunao. Sales experience public speaking naturally behtar karta hai."),
    (["body language","jism ki zubaan","posture","expression"],
     "Body language mein: seedha kharo, eye contact rakho, smile karo, open body posture rakho aur fidgeting se bacho. 55% communication body language hai!"),
    (["listening skills","sunna","active listening","dhyan se sunna"],
     "Active listening mein: phone band karo, poori baat suno, beech mein mat katao, notes lo aur repeat karo jo unhone kaha. Customer appreciate karta hai."),
    (["email writing","email likhna","professional email"],
     "Professional email mein: subject clear rakho, short aur to-the-point likho, polite tone rakho aur clear CTA do. Grammar check karo. Sales email mein benefit highlight karo."),

    # ── CAREER GROWTH ────────────────────────────────────────────
    (["career growth","taraqqi","promotion","aage badhna"],
     "Sales mein taraqqi ke liye: target consistently poora karo, naye skills seekho, manager ko impress karo, networking karo aur leadership show karo."),
    (["sales manager","manager banna","leadership","team lead"],
     "Sales Manager banne ke liye: consistently best performer bano, team ko help karo, reporting accurate rakho aur manager ki responsibilities khud lene shuroo karo."),
    (["salary increase","talkha badhaana","raise lena","zyada salary"],
     "Salary increase ke liye: apni performance data show karo, market rate research karo, timing theek chuno (after target completion) aur confidently negotiate karo."),
    (["interview","job interview","sales job interview"],
     "Sales job interview mein: past targets aur achievements batao, rejection handle karna dikhao, role play ke liye tyaar raho aur enthusiasm show karo."),
    (["resume cv","CV banana","sales resume"],
     "Sales CV mein: quantified achievements likho (e.g. 'Monthly target 120% achieve kiya'), skills, experience aur references shamil karo. Short aur impact-ful rakho."),
    (["freelancing","freelance sales","remote sales","ghar se kaam"],
     "Freelance sales mein: online clients dhoondho, Upwork/Fiverr try karo, commission-based remote kaam karo ya apna WhatsApp/Facebook business chalao."),
    (["courses","training","sales training","seekhna"],
     "Sales training ke liye: YouTube mein free courses hain, Coursera, Udemy par bhi available hain. Pakistani trainers jaise Qasim Ali Shah ko follow karo."),

    # ── MONEY & FINANCE ──────────────────────────────────────────
    (["savings","bachat","paisay bachana","save money"],
     "Paisay bachane ke liye: income ka 20% hamesha pehle side rakho, zaroorat aur farmaish mein farq karo, budget banao aur unnecessary kharcha band karo."),
    (["tax","income tax","FBR","tax return"],
     "Pakistan mein agar aap kama rahe hain toh tax return FBR par file karni chahiye. NTN number lein aur accountant ki madad lein."),
    (["bank account","account khulwana","banking"],
     "Bank account ke liye: CNIC le kar kisi bhi bank jaen. HBL, MCB, Meezan Mailsi mein hain. Mobile banking se ghar se kaam ho jaata hai."),
    (["mobile payment","easypaisa","jazzcash","online payment"],
     "EasyPaisa aur JazzCash Pakistan mein bohat popular digital payment platforms hain. Customer bhi easily pay kar sakta hai. Sales collections fast ho jaati hain."),
    (["loan","qarz","bank loan","asaan loan"],
     "Loan lene se pehle: interest rate compare karo, wapsi ki capacity check karo. Kamyab Jawan, SMEDA ya bank se apply karo. Guarantee/collateral lag sakti hai."),

    # ── PAKISTAN GENERAL ─────────────────────────────────────────
    (["pakistan economy","pakistan karobar","business pakistan"],
     "Pakistan mein small businesses aur sales kaafi flourishing hain. FMCG, real estate, textile aur agri-sectors mein sales jobs ki bahut demand hai."),
    (["mehngai","inflation","prices barh rahe","mahanga"],
     "Mehngai mein sales strategy adjust karo: value emphasize karo, installment options do aur budget-friendly variants offer karo. Customer ki purchasing power ka khayal rakho."),
    (["internet","technology","digital","online tools"],
     "Digital tools se sales boost hoti hai. WhatsApp, Facebook, Instagram, OLX — yeh sab free platforms hain. Internet ne door-to-door se zyada reach de di hai."),
    (["petrol","transport cost","safar ka kharcha","fuel"],
     "Field sales mein petrol ka kharcha zyada hota hai. Route planning se fuel bachao. Company vehicle ya allowance mangna manager se discuss karo."),
    (["eid","ramzan","special occasions","tyohaar"],
     "Eid aur Ramzan mein sales boom aati hai. Pehle se plan karo, stock rakho, special deals banao aur existing customers ko remind karo. Yeh peak season hai!"),

    # ── MOTIVATION ───────────────────────────────────────────────
    (["motivation","hausla","inspire","umeed","struggling"],
     "Sales mushkil hai par rewarding hai. Yaad rakho: har successful Sales Man ne saikron 'na' sune hain. Uthao aur phir try karo. Aapka kal aaj se behtar hoga! 💪"),
    (["stress","tension","pareshan","thak gaya","burnout"],
     "Sales stress mein: chhoti jeetein celebrate karo, break lo, exercise karo aur trusted dost se baat karo. Stress normal hai — manage karna seekho."),
    (["failure","naakaam","haar gaya","galti"],
     "Failure seekhne ka zariya hai. Har galti ek lesson hai. Analyse karo kya galat hua, fix karo aur aage badho. Successful log zyada fail hote hain — woh ruke nahi."),
    (["success","kamyabi","jeet","achieve"],
     "Kamyabi ke liye: clear goals rakho, daily action lo, consistent raho aur sabr rakho. Muhammad Naeem jaise log mehnat se hi aage badhte hain!"),
    (["hard work","mehnat","koshish","lagan"],
     "Mehnat ka koi shortcut nahi. Sales mein woh aage jaata hai jo sabse zyada koshish karta hai. Roz thoda behtar bano — time ke saath results aate hain."),

    # ── GREETINGS / FAREWELLS ────────────────────────────────────
    (["hello","hi","salam","assalam","adaab","hey","aoa"],
     f"Salam! Main {OWNER_INFO['name']} ka Sales Chatbot hun 👋 Sales, marketing ya karobar ke barey mein koi bhi sawaal poochhein!"),
    (["shukriya","thank you","thanks","meherbani","jazakallah"],
     "Bahut shukriya! Koi aur sawaal ho toh zaroor poochhein. Hum hamesha haazir hain! 😊"),
    (["bye","khuda hafiz","alvida","goodbye","chalta hun","nikal raha"],
     f"Allah Hafiz! {OWNER_INFO['name']} se rabta karein: {OWNER_INFO['contact']} | Mailsi 📞"),
    (["help","madad","kya poochhun","guide","kya bata sakte"],
     "Aap pooch sakte hain: sales tips, marketing ideas, customer handling, Mailsi info, career advice, motivation ya koi bhi sales related sawaal!"),
    (["kaisa ho","how are you","theek ho","kya haal"],
     "Main bilkul theek hun, shukriya! Aap kaise hain? Sales ya karobar se related koi masla ho toh zaroor batayein! 😊"),
    (["joke","mazaak","funny","hansi","latifa"],
     "Ek Sales Man ne manager se kaha: 'Mera customer kehta hai sochega!' Manager: 'Beta, sochega matlab nahi hota hai — agli call karo!' 😄"),
    (["subah","good morning","morning","sawera"],
     f"Good Morning! Ek naya din, naye customers, naye opportunities! {OWNER_INFO['name']} ka Sales Bot aapki khidmat mein haazir hai. Aaj kya poochna hai?"),
    (["raat","good night","night","sona"],
     "Good Night! Aaj ki sales report ready kar lein aur kal ke liye targets set kar lein. Aaram karo — kal phir full energy ke saath aana hai! 🌙"),
]
